### ISSUE TITLE
Filtering for PDM Mic

### ISSUE THREAD

**Issue by lucas-andersen** [sandeepmistry/pico-microphone#10]
Hello,

I would really appreciate if you explained the filtering that is implemented for the PDM microphone. Should I be concerned at all about aliasing when using the PDM microphone for an audio classification task with potential sounds above 8kHz? Thanks!

**Comment by sandeepmistry** [comment]
Hi @lucas-andersen,

I'm not overly familiar with the filtering code, the code was taking from here: https://os.mbed.com/teams/ST/code/X_NUCLEO_CCA02M1//file/53f8b511f2a1/Middlewares/OpenPDM2PCM/

Are you experiencing any aliasing?
