### ISSUE TITLE
Use Micropython With microphone library

### ISSUE THREAD

**Issue by alirezadigi** [sandeepmistry/pico-microphone#12]
Hi. How can i use micropython firmware alongside a Max9814 , with this module?
Any Solutions?

I have written the code below but cant hear clear voice in audacity...
```python
from machine import Pin, ADC
import ustruct , time

analog_value = machine.ADC(26)
conversion_factor =3.3/(65536)

samples = []

while True:
    reading = analog_value.read_u16()*conversion_factor   
samples.append(int(reading)) #print("ADC: ",reading)
time.sleep(0.002)



with open('Voice.bin', 'wb') as output:
     for sample in samples:
        output.write(struct.pack('<h', sample))

```

**Comment by alirezadigi** [comment]
Or even use this microphone library near MicroPython...

**Comment by sandeepmistry** [comment]
Hi @alirezadigi,

You would have to create a [Native machine .mpy file](https://docs.micropython.org/en/latest/develop/natmod.html) which bridges this library to MicroPython.

This is out of scope of this project.

**Comment by alirezadigi** [comment]
@sandeepmistry thanks 
sorry can you please help me with the python code? ...

**Comment by sandeepmistry** [comment]
Hi @alirezadigi, unfortunately since it is out of scope for this project, I cannot help with your request.
