### ISSUE TITLE
Can it work with?

### ISSUE THREAD

**Issue by Lanson2232** [sandeepmistry/pico-microphone#21]
So Actually I'm trying to create a "Sound card" for my Electric Guitar but it didn't work with [this Elektret microphone](https://www.robotistan.com/ses-sensor-karti-mikrofon-sensoru) aka. Sound sensor? isn't it compatible or do I need do something I would use PDM but this sort of microphone modules are much easier to replace or solder on it
I don't get any soundwave on audacity just a straight line

**Comment by sandeepmistry** [comment]
Hi @Lanson2232,

Could you please provide more details on the example or code you are trying to use?

The microphone you linked could be used with the API's in [analog_microphone.h](https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/blob/main/src/include/pico/analog_microphone.h).

**Comment by kannel-outis** [comment]
@Lanson2232 your microphone only gives an output of only 0s and 1s... 0 for no sound and 1 for sound... It's not compatible for what you want to use it for. It only senses sound

**Comment by Lanson2232** [comment]
> @Lanson2232 your microphone only gives an output of only 0s and 1s... 0 for no sound and 1 for sound... It's not compatible for what you want to use it for. It only senses sound

Well that makes sense. Anyway thanks for helping both. I did create "Sound Card" or "Guitar mic" by making an basic AMP circuit that makes analog to analog to my computer
