### ISSUE TITLE
Multichannel Analog USB Microphone

### ISSUE THREAD

**Issue by Sky-Unmodal** [sandeepmistry/pico-microphone#24]
I followed CaydenPierce's four channel PDM usb microphone array format from: https://github.com/CaydenPierce/MSA to create a similar firmware that use Analog microphones instead of PDM microphones. 

The board I was using is waveshare_rp2040_lcd_1.28.

I was able to get signals from the ADC pins and receive four channel audio data on my machine via USB.

However, I encountered some issues:
1. Received the same signal across different channels. [I expected it to show different signals from different channels because they are using different ADC pins]
2. Even if I did not initialize a ADC pin, for example, GPIO26 from rp2040, i could still get the signal from that pin regardless. And this also has the issue I described above issue 1. [I expected it to not be able to read from GPIO26 because I did not initialize that pin to read from]

Could anyone provide some feedback on this? It might due to my implementation is wrong but if someone can point me in the right direction, that would be very helpful.

Thanks in advance!

**Comment by sandeepmistry** [comment]
Hi @Sky-Unmodal,

I don't have any experience with this, I would suggest you follow up with CaydenPierce directly.
