### ISSUE TITLE
when is on_usb_microphone_tx_ready() called?

### ISSUE THREAD

**Issue by petercwallis** [sandeepmistry/pico-microphone#25]
In /examples/usb_microphone/main.c there is a sample_buffer of 256 int16_t that I assume gets passed to the usb tx process with the above call.  I was expecting it to get called when the other end of the usb serial connection ran out of data - so about 16000/256 times a second? I have tried using a for loop to fill the sample buffer with rubbish on each call but the usb microphone locks. That is, arecord -d 3 test.wav does not terminate until the usb something or other times out. Can anyone tell me what I am missing here?

**Comment by sandeepmistry** [comment]
Hi @petercwallis,

I have not tried with `arecord`, would you be able to try with Audacity: https://www.hackster.io/sandeep-mistry/create-a-usb-microphone-with-the-raspberry-pi-pico-cc9bd5#toc-recording-audio-data-8

If that works `aplay` might need some additional parameters for set up the correct sample rate and bits.
