### ISSUE TITLE
Reading raw PDM data

### ISSUE THREAD

**Issue by jessica-brown** [sandeepmistry/pico-microphone#29]
Hi, 

Is it possible to output the raw PDM data directly to the serial monitor using these examples? I would like to implement my own filter on the incoming PDM signal in post processing, but I'm not proficient in C so struggling a bit to get the raw data easily. 

Thanks!

**Comment by sandeepmistry** [comment]
Hi @jessica-brown,

The unfiltered data can be found in the `pdm_microphone_read` function, in the `in` variable before `Open_PDM_Filter_64`/`Open_PDM_Filter_128` is called.

https://github.com/ArmDeveloperEcosystem/microphone-library-for-pico/blob/a837f633a6ad2bac268349df35d57e46e551f416/src/pdm_microphone.c#L232
