### ISSUE TITLE
Support for Adafruit I2S MEMS Microphone Breakout - SPH0645LM4H

### ISSUE THREAD

**Issue by fredsco** [sandeepmistry/pico-microphone#35]
I'm wondering if there is support for the -> https://www.adafruit.com/product/3421 this Breakout board has  LRCL, DOUT and BCLK

**Comment by sandeepmistry** [comment]
Hi @fredsco,

That microphone is not supported as it uses an I2S interface, only microphones with a PDM or analog interface are supported.
